### ISSUE TITLE
[BUG] Selecting a Snapahot causes the system to crash and restart all.

### ISSUE THREAD

**Issue by maarthome** [rerdavies/pipedal#207] opened 2024-10-07 04:46 UTC
**Describe the bug**
Selecting a Snapahot causes the system to crash and restart all.

**Screenshots**
Oct 07 05:39:19 pipedal systemd[1]: pipedald.service: Main process exited, code=killed, status=11/SEGV
Oct 07 05:39:19 pipedal systemd[1]: pipedald.service: Failed with result 'signal'.
Oct 07 05:39:19 pipedal systemd[1]: pipedald.service: Consumed 1.724s CPU time.
Oct 07 05:39:24 pipedal systemd[1]: pipedald.service: Scheduled restart job, restart counter is at 10.
Oct 07 05:39:24 pipedal systemd[1]: Stopped pipedald.service - PiPedal Web Service.
Oct 07 05:39:24 pipedal systemd[1]: pipedald.service: Consumed 1.724s CPU time.
Oct 07 05:39:24 pipedal systemd[1]: Starting pipedald.service - PiPedal Web Service...
Oct 07 05:39:24 pipedal pipedald[1474]: Document root: /etc/pipedal/config Threads: 5
Oct 07 05:39:24 pipedal pipedald[1474]: Locale: en_GB
Oct 07 05:39:24 pipedal pipedald[1474]: Updater: Next update check at 2024-10-07 13:29:47
Oct 07 05:39:24 pipedal pipedald[1474]: Scanning for LV2 Plugins
Oct 07 05:39:25 pipedal systemd[1]: Started pipedald.service - PiPedal Web Service.
Oct 07 05:39:25 pipedal pipedald[1474]: Waiting for ALSA device hw:Mobile.
Oct 07 05:39:35 pipedal pipedald[1474]: ALSA device hw:Mobile not found.
Oct 07 05:39:35 pipedal authbind[1474]: ALSA lib confmisc.c:165:(snd_config_get_card) Cannot get card index for Mobile
Oct 07 05:39:36 pipedal authbind[1474]: ALSA lib confmisc.c:165:(snd_config_get_card) Cannot get card index for Mobile
Oct 07 05:39:37 pipedal pipedald[1474]: Failed to start audio. hw:Mobile playback device not found. (No such device)
Oct 07 05:39:37 pipedal pipedald[1474]: Audio started. DUMMY, n/a, Native float, 48000, 64x3, in: 2/2, out: 2/2
Oct 07 05:39:37 pipedal pipedald[1474]: Listening on mDns address pipedal:80
Oct 07 05:39:37 pipedal pipedald[1474]: Listening on Wi-Fi address 192.168.1.243:80
Oct 07 05:39:37 pipedal pipedald[1474]: DNS/SD service announced. (pipedal)
Oct 07 05:39:38 pipedal pipedald[1474]: DNS/SD group established.
Oct 07 05:39:38 pipedal pipedald[1474]: HotspotManager: Monitoring network status.
Oct 07 05:39:48 pipedal pipedald[1474]: Listening on mDns address pipedal:80
Oct 07 05:39:48 pipedal pipedald[1474]: Listening on Wi-Fi address 192.168.1.243:80

** Environment (please complete the following information):**
Linux pipedal 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux

 - Device that the pipedal server is running on (pi 3, pi 4, &c, how much system memory)
 Pi5 4GB 
 - PiPedal Version [See X/Settings/About,...]

**Comment by rerdavies** [comment] 2024-10-09 18:16
Fixed in v1.3.54. Please feel free to re-open this bug (or create a new one) if the problem isn't resolved.

**Closed by rerdavies** 2024-10-09 18:16 UTC
Labels: bug
